### ISSUE TITLE
Suggestion for more booleans

### ISSUE THREAD

**Issue by eggbean** [gerazov/vim-toggle-bool#1]
Hi. Finding this useful, but it would be very nice if you added support for:

* on / off
* yes / no
* enable / disable

..that would be great.

A similar vim plugin does two of those, but it still seems to use python 2, so I'd prefer to use your vimscript plugin.

Cheers.

**Comment by eggbean** [comment]
Okay, just realised it was very easy to do myself. Thanks.

**Comment by gerazov** [comment]
Maybe do a PR?

**Comment by eggbean** [comment]
Sure. You might want to clean up the README.md though.

https://github.com/gerazov/vim-toggle-bool/pull/2

**Comment by gerazov** [comment]
Awesome :sunglasses: thanks! :pray:

**Comment by eggbean** [comment]
Sorry, I missed a comma out in configuration in the `README.md`.

I have fixed it in this updated version and added another line so capitalised TRUE / FALSE is supported.

Thank you.
